<a href="https://colab.research.google.com/github/Noor72353/Iris_ML_Project/blob/main/ML_Project_Comparison.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Machine Learning Classification Project

Comparison of Three Supervised Machine Learning Algorithms:
1. K-Nearest Neighbors (KNN)
2. Logistic Regression
3. Decision Tree

Dataset Used: Iris Dataset

Objective:
To apply three supervised machine learning algorithms on the same dataset and compare their performance using evaluation metrics such as Accuracy, Precision, Recall, and F1-Score.

Step 0: Import Required Libraries

In this step, all necessary Python libraries are imported.

Scikit-learn provides machine learning algorithms and evaluation metrics.
Pandas is used for handling tabular data.
These libraries will be used throughout the project.

In [40]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

Step 1: Load the Dataset

The Iris dataset is loaded from the Scikit-learn library.

The dataset contains 150 flower samples belonging to three different species:
- Setosa
- Versicolor
- Virginica

Each sample contains four numerical features:
- Sepal Length
- Sepal Width
- Petal Length
- Petal Width

In [39]:
from sklearn.datasets import load_iris

iris = load_iris()

print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

Display Dataset Features and Target Labels

The first few feature values and corresponding target labels are displayed.

In [3]:
from sklearn.datasets import load_iris

iris = load_iris()

print("Features:")
print(iris.data[:5])

print("\nTarget:")
print(iris.target[:5])

Features:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Target:
[0 0 0 0 0]


Step 2: Separate Features and Target

X contains the input features.

y contains the target labels.

In [4]:
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target

print("X Shape:", X.shape)
print("y Shape:", y.shape)

X Shape: (150, 4)
y Shape: (150,)


Display the First Record

The first flower sample and its corresponding class label are displayed.

In [5]:
print("First Flower Features:")
print(X[0])

print("First Flower Class:")
print(y[0])

First Flower Features:
[5.1 3.5 1.4 0.2]
First Flower Class:
0


Step 3: Train-Test Split

The dataset is divided into training and testing sets.

80% Training Data
20% Testing Data

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [9]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (120, 4)
X_test shape: (30, 4)
y_train shape: (120,)
y_test shape: (30,)


Step 4: Apply K-Nearest Neighbors (KNN)

KNN classifies a sample based on the majority vote of its nearest neighbors.

In this project, K = 3.

In [11]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)

In [12]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [13]:
y_pred_knn = knn.predict(X_test)

In [14]:
print("Actual Classes:")
print(y_test[:10])

print("\nPredicted Classes:")
print(y_pred_knn[:10])

Actual Classes:
[1 0 2 1 1 0 1 2 1 1]

Predicted Classes:
[1 0 2 1 1 0 1 2 1 1]


KNN Evaluation

The accuracy of the KNN model is calculated.

In [15]:
from sklearn.metrics import accuracy_score

In [16]:
acc_knn = accuracy_score(y_test, y_pred_knn)

print("KNN Accuracy:", acc_knn)

KNN Accuracy: 1.0


In [17]:
print("KNN Accuracy Percentage:", acc_knn * 100, "%")

KNN Accuracy Percentage: 100.0 %


KNN Confusion Matrix

The confusion matrix is used to evaluate the classification performance of the K-Nearest Neighbors (KNN) model.

Rows represent the actual classes, while columns represent the predicted classes.

Correct predictions appear on the diagonal of the matrix.

In [33]:
from sklearn.metrics import confusion_matrix

cm_knn = confusion_matrix(y_test, y_pred_knn)

print(cm_knn)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


KNN Classification Report

The classification report provides detailed performance metrics of the KNN model.

Metrics included:
• Precision
• Recall
• F1-Score
• Support

These metrics help evaluate the quality of classification beyond simple accuracy.

In [34]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



Step 5: Logistic Regression

Logistic Regression is a classification algorithm that predicts the probability of each class.

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
lr = LogisticRegression(max_iter=200)

In [20]:
lr.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [21]:
y_pred_lr = lr.predict(X_test)

In [22]:
print("Actual Classes:")
print(y_test[:10])

print("\nPredicted Classes:")
print(y_pred_lr[:10])

Actual Classes:
[1 0 2 1 1 0 1 2 1 1]

Predicted Classes:
[1 0 2 1 1 0 1 2 1 1]


Logistic Regression Evaluation:

The accuracy of the Logistic Regression model is calculated:

In [23]:
acc_lr = accuracy_score(y_test, y_pred_lr)

print("Logistic Regression Accuracy:", acc_lr)

Logistic Regression Accuracy: 1.0


In [24]:
print("Logistic Regression Accuracy Percentage:", acc_lr * 100, "%")

Logistic Regression Accuracy Percentage: 100.0 %


Logistic Regression Confusion Matrix

The confusion matrix is generated to evaluate the classification performance of the Logistic Regression model.

It compares the actual class labels with the predicted class labels and helps identify correct and incorrect classifications.

In the confusion matrix:
- Rows represent actual classes.
- Columns represent predicted classes.
- Values on the diagonal indicate correct predictions.

In [37]:
cm_lr = confusion_matrix(y_test, y_pred_lr)

print(cm_lr)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


Logistic Regression Classification Report:

The classification report summarizes the performance of the Logistic Regression model using Precision, Recall, F1-Score, and Support.

These metrics provide a detailed evaluation of the model's classification capability.

In [35]:
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



Step 6: Decision Tree

Decision Tree classifies data using a tree-like structure of decisions.

In [25]:
from sklearn.tree import DecisionTreeClassifier

In [26]:
dt = DecisionTreeClassifier(random_state=42)

In [27]:
dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [28]:
y_pred_dt = dt.predict(X_test)

In [29]:
print("Actual Classes:")
print(y_test[:10])

print("\nPredicted Classes:")
print(y_pred_dt[:10])


Actual Classes:
[1 0 2 1 1 0 1 2 1 1]

Predicted Classes:
[1 0 2 1 1 0 1 2 1 1]


Decision Tree Evaluation:

The accuracy of the Decision Tree model is calculated:

In [30]:
acc_dt = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy:", acc_dt)

Decision Tree Accuracy: 1.0


In [31]:
print("Decision Tree Accuracy Percentage:", acc_dt * 100, "%")

Decision Tree Accuracy Percentage: 100.0 %


Decision Tree Confusion Matrix

The confusion matrix is used to evaluate the classification performance of the Decision Tree model.

It compares actual class labels with predicted class labels and shows the number of correct and incorrect predictions.

In the confusion matrix:
- Rows represent actual classes.
- Columns represent predicted classes.
- Values on the diagonal indicate correct classifications.

In [38]:
cm_dt = confusion_matrix(y_test, y_pred_dt)

print(cm_dt)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


Decision Tree Classification Report

The classification report presents Precision, Recall, F1-Score, and Support for the Decision Tree model.

These evaluation metrics provide a comprehensive assessment of model performance.

In [36]:
print(classification_report(y_test, y_pred_dt))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



Performance Comparison

The final accuracies of all three machine learning algorithms are compared below.
This comparison helps identify the best-performing model for the Iris dataset.

In [32]:
import pandas as pd

results = pd.DataFrame({
    'Algorithm': ['KNN', 'Logistic Regression', 'Decision Tree'],
    'Accuracy': [acc_knn, acc_lr, acc_dt]
})

print(results)

             Algorithm  Accuracy
0                  KNN       1.0
1  Logistic Regression       1.0
2        Decision Tree       1.0


Conclusion

KNN, Logistic Regression, and Decision Tree were applied to the Iris dataset.

All three algorithms achieved 100% accuracy on the testing dataset.

Therefore, all models performed equally well on this dataset and no single algorithm outperformed the others.